#![cfg_attr(docsrs, feature(doc_auto_cfg))]

#[cfg(feature = "postgres")]
pub use self::int::{U15, U31, U63};
#[cfg(feature = "derive")]
pub use benzina_derive::{Enum, join};

#[doc(hidden)]
#[cfg(feature = "derive")]
pub mod __private;
#[cfg(feature = "postgres")]
pub mod error;
#[cfg(feature = "example-generated")]
/// This module shows an example of code generated by the [`typed_uuid`] macro. IT **MUST NOT BE
/// USED OUTSIDE THIS CRATE**.
pub mod example_generated;
#[cfg(feature = "postgres")]
mod int;
#[cfg(all(feature = "serde", feature = "postgres"))]
mod serde;
#[cfg(feature = "typed-uuid")]
mod typed_uuid;
#[cfg(all(feature = "utoipa", feature = "postgres"))]
mod utoipa;
