#![cfg_attr(docsrs, feature(doc_cfg))]

#[cfg(feature = "derive")]
pub use benzina_derive::{Enum, join};

#[cfg(feature = "array")]
pub use self::array::{Array, ArrayWithNullableItems};
#[cfg(feature = "postgres")]
pub use self::at_time_zone::{
    AtTimeZone, FromInstant, FromUtc, InstantLike, TimeZone, at_time_zone,
};
#[cfg(feature = "postgres")]
pub use self::binary::Binary;
#[cfg(feature = "ctid")]
pub use self::ctid::{Ctid, ctid};
#[cfg(feature = "postgres")]
pub use self::date_eq::{
    ClosedRange, DateEq, DateLike, DateOnly, ExtractedDate, HalfOpenRange, extract_date,
};
#[cfg(feature = "postgres")]
pub use self::date_part::{
    DateOrTimestamp, DatePartBetween, DatePartEq, DayPart, MonthPart, YearPart, YearRange,
    extract_day, extract_month, extract_year,
};
pub use self::either::Either;
#[cfg(feature = "postgres")]
pub use self::int::{U15, U31, U63};
#[cfg(feature = "json")]
pub use self::json::{
    Json,
    binary::Jsonb,
    nullable::{NullableJson, NullableJsonb},
};
#[cfg(feature = "postgres")]
pub use self::time_eq::{BareTime, CastToTime, ExtractedTime, TimeEq, TimeLike, extract_time};

#[doc(hidden)]
pub mod __private;
#[cfg(feature = "array")]
mod array;
#[cfg(feature = "postgres")]
mod at_time_zone;
#[cfg(feature = "postgres")]
mod binary;
#[cfg(feature = "ctid")]
mod ctid;
#[cfg(feature = "postgres")]
mod date_eq;
#[cfg(feature = "postgres")]
mod date_part;
mod either;
#[cfg(feature = "postgres")]
pub mod error;
#[cfg(feature = "example-generated")]
/// This module shows an example of code generated by the [`typed_uuid`] macro. IT **MUST NOT BE
/// USED OUTSIDE THIS CRATE**.
pub mod example_generated;
#[cfg(feature = "postgres")]
mod int;
#[cfg(feature = "json")]
mod json;
#[cfg(all(feature = "schemars", feature = "postgres"))]
mod schemars;
#[cfg(all(feature = "serde", feature = "postgres"))]
mod serde;
#[cfg(feature = "postgres")]
pub mod sql_types;
#[cfg(feature = "postgres")]
mod time_eq;
#[cfg(feature = "typed-uuid")]
mod typed_uuid;
#[cfg(all(feature = "utoipa", feature = "postgres"))]
mod utoipa;
