#![cfg_attr(docsrs, feature(doc_cfg))]

#[cfg(feature = "derive")]
pub use benzina_derive::{Enum, join};

#[cfg(feature = "array")]
pub use self::array::{Array, ArrayWithNullableItems};
#[cfg(feature = "ctid")]
pub use self::ctid::{Ctid, ctid};
#[cfg(feature = "postgres")]
pub use self::int::{U15, U31, U63};
#[cfg(feature = "json")]
pub use self::json::{
    Json,
    binary::Jsonb,
    nullable::{NullableJson, NullableJsonb},
};

#[doc(hidden)]
pub mod __private;
#[cfg(feature = "array")]
mod array;
#[cfg(feature = "ctid")]
mod ctid;
#[cfg(feature = "postgres")]
pub mod error;
#[cfg(feature = "example-generated")]
/// This module shows an example of code generated by the [`typed_uuid`] macro. IT **MUST NOT BE
/// USED OUTSIDE THIS CRATE**.
pub mod example_generated;
#[cfg(feature = "postgres")]
mod int;
#[cfg(feature = "json")]
mod json;
#[cfg(all(feature = "schemars", feature = "postgres"))]
mod schemars;
#[cfg(all(feature = "serde", feature = "postgres"))]
mod serde;
#[cfg(feature = "postgres")]
pub mod sql_types;
#[cfg(feature = "typed-uuid")]
mod typed_uuid;
#[cfg(all(feature = "utoipa", feature = "postgres"))]
mod utoipa;
